### ISSUE TITLE
Gumtree login page

### ISSUE THREAD

**Issue by jamielatham15** [anasyusef/gumtree-scraper#1]
Playing around with this, its great! 

Sadly the scraper fails as Gumtree demands the user login after about three pages.

Is there any way to login to gumtree prior to initiating the scraping, or circumventing the login page entirely?

Many thanks

**Comment by anasyusef** [comment]
Hello There,

The program has not been actively maintained, so I am not sure if it still works. However, what you can try is to sleep the program for a specific amount of time, so it gives you time to login. There are better ways to do this functionality, but I think this is the simplest one.

Kind Regards,
Anas Yousef

On 11 Feb 2018, at 14:48, Jamie Latham <notifications@github.com<mailto:notifications@github.com>> wrote:


Playing around with this, its great!

Sadly the scraper fails as Gumtree demands the user login after about three pages.

Is there any way to login to gumtree prior to initiating the scraping, or circumventing the login page entirely?

Many thanks

**Comment by jamielatham15** [comment]
Dear Anas,

I ended up adding the following to the 'main' function at the top of the GumtreeScraper.py. 

This needs to follow the initial definitions (specifically `driver = webdriver.Chrome()`)

    ```
    driver.get("https://my.gumtree.com/login") 
    time.sleep(5)
    username = driver.find_element_by_id("email")
    password = driver.find_element_by_id("fld-password")
    username.send_keys(email)
    password.send_keys(password)
    login_attempt = driver.find_element_by_xpath('//*[@id="login-form"]/div/form/fieldset/div[3]/button')
    login_attempt.click()
    time.sleep(20)
```

the long sleep at the end is necessary as sometimes the login page throws up a picture captcha to complete before login.

Works perfectly now - much appreciated.

Jamie
